### ISSUE TITLE
SSO Module not working without quotes around accept_all_certs boolean value

### ISSUE THREAD

**Issue by afewell** [vmware/nsxansible#41] opened 2017-01-17 20:11 UTC
I ran the test_sso_registration.yml play and ran into parsing errors around the boolean value for the accept_all_certs variable. I then tried running it with the boolean value wrapped in quotes like `accept_all_certs: "True"` and once I did that it ran just fine. 

AFAIK nobody else has tested or attempted to replicate this error, but I am seeing it consistently on my current build, which I cloned from the master branch a few days ago. 

![nsxansible_error](https://cloud.githubusercontent.com/assets/17549071/22037940/13a00b64-dcae-11e6-9547-f7c6e434b582.png)

**Comment by yasensim** [comment] 2017-04-07 10:40
@afewell you wrote test_sso_registration but on the screenshot you are showing vc_registration.
Do you see the same problem with sso_reg? Could you share your ansible and python versions please?
I dont see this issue in my setup but think I can fix it as I see the difference between sso and vc registration in the library.

**Comment by yfauser** [comment] 2017-06-02 13:36
@afewell I'm closing this for now as Yasen can't reproduce it. Please re-open if you run into this again

**Closed as completed by yfauser** 2017-06-02 13:36 UTC

**Comment by afewell** [comment] 2017-07-28 13:05
Hey Guys, sorry for my delayed response ... I didnt realize these emails
were getting buried in my personal email account. Thanks so much for taking
care of the issue!
